github:
  user_or_org: gouarin
travis:
  secure:
    BINSTAR_TOKEN: oVuaTwkie9URIofzQaH1tjcXYqbnDDuLp7MMGOeilFQufD/ivOZClSGomBUVo337hjD5q0eDvIJCyXKz3TCAn5RaZuHkxUcMGJ1UAA7RWuZ/J+zAgFdYFcuB+QAC1scQ6yXfb20br6B39EO1wMsQpc0vDsxA7DSeFFtHDpye5uZLdWYqTnIL7BXsb7RqRCPk1nMzZw9Wc0YLnZ+QrCRJkjFUYqsc2K46pYAy1WmLS1A7ozSANTv2ZL3N0SpW3uFx/++zr5s5KGOeKgvMNRtANEaeb5MZeFYv3hXJgw5foWDSY6WC2Ao2E225diejoGNrKsczAOJgVDW2+8kr+w3v4ugybo0FP8Dx6fjTFzYmElZdJ0Es5meLK6s7Tx5mDbfeRz2LzIFsQ08iRuOLhc8xsVI+2pkZfeq2XBiJOexLrGsdsh1JdjbqtVAXWm/CH1P0Pakp42sepuiWTbhxFrd5Xf72sGXs4ceLmV3WgA2TBsk4tiKO/5vj7AJjlBapQuj/i/CHB41/7a3YVa1DJ+OYbOVc8q6M6EWuadLDcXDm+/qDa2pNeuMLRJ0ShnBwmx+EMnWjCoCxFhoJuulLr3nfkDviHpbxn2ev2oxZCqX8YVCgcFyZ92rdvI/h18CSTfrtDyY8Mt4/6gCrszoVRNtzTQd8sCO5Jj7EjWuNSMtcAC8=
appveyor:
  secure:
    BINSTAR_TOKEN: IgQ0ihtOWOGDj+VRskpoImtpJQaF9LAAwD0rA9/xQXa7fIr3N8+hQM8aAMi/zXC/
